""" MONITORING DB
"""

# access from python
MONITORING_CLIENT = None
MONITORING_URL = "localhost"
MONITORING_PORT = 2424
MONITORING_USER = "technical"
MONITORING_PASS = "password"
MONITORING_DBNAME = "experiment_monitoring"
# tables in database

MONITORING_GDB_TABLE = "GRAPHDB"
MONITORING_MEAS_TABLE = "MEASUREMENT"
MONITORING_CONF_TABLE = "CONFIGURATION"
MONITORING_TYPE_TABLE = "TYPES"
MONITORING_EXP_TABLE = "EXPERIMENT"
MONITORING_ITE_TABLE = "ITERATION"
MONITORING_VAL_TABLE = "MEASUREMENT_VALUE"


MONITORING_DB_TABLE = "graph_databases"
MONITORING_REC_TABLE = "records"
MONITORING_EXPER_TABLE = "experiments_types"
MONITORING_VALUE_TABLE = "experiments_values"
