""" ARANGO DB
"""

# access from HTTP API
GRAPHDB_API_URL = ""
GRAPHDB_API_USER = ""
GRAPHDB_API_PASS = ""
GRAPHDB_API_DBNAME = ""
GRAPHDB_DB_LIST = ""
GRAPHDB_DB_CREATE = ""
GRAPHDB_DB_DROP = ""
GRAPHDB_DB_EXPORT = ""
GRAPHDB_DB_BATCH = ""
GRAPH_DB_COMMAND = ""
GRAPHDB_DB_IMPORT = ""
GRAPHDB_DB_SIZE = ""
GRAPHDB_DB_SCHEMA = ""
 
